### ISSUE TITLE
can't 'import Cairo' after I ' brew install Cairo '

### ISSUE THREAD

**Issue by hova88** [Elteoremadebeethoven/AnimationsWithManim#1]

**Comment by Elteoremadebeethoven** [comment]
Please send a screenshot of your terminal

**Comment by hova88** [comment]
> Please send a screenshot of your terminal

I already solved the problem by running 'conda install pycairo' in terminal. This is mainly due to the 'requirements.txt' in 3b1b/Manim does not conform to  pycairo version for OS X.

**Comment by Elteoremadebeethoven** [comment]
Perfect
