### ISSUE TITLE
RemoveBackgroundStrokeWidth----it  doesn't work

### ISSUE THREAD

**Issue by barakasamsara** [Elteoremadebeethoven/AnimationsWithManim#10]
source code:

class RemoveBackgroundStrokeWidth(ChangeBackgroundColor):
    CONFIG={
        "text":TexMobject(
            r"\frac{d}{dx}\Bigr|_{y=2}",
            background_stroke_width=0, #<- Add this line
            ).scale(5)
    }

$ python3 -m manim ***.py RemoveBackgroundStrokeWidth -pl
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/***/Desktop/manim-master/manim.py", line 5, in <module>
    manimlib.main()
  File "/Users/***/Desktop/manim-master/manimlib/__init__.py", line 11, in main
    config = manimlib.config.get_configuration(args)
  File "/Users/***/Desktop/manim-master/manimlib/config.py", line 185, in get_configuration
    module = get_module(args.file)
  File "/Users/***/Desktop/manim-master/manimlib/config.py", line 180, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "*****.py", line 19, in <module>
    class RemoveBackgroundStrokeWidth(ChangeBackgroundColor):
NameError: name 'ChangeBackgroundColor' is not defined

and btw....
if i don't wanna put the order"background_stroke_width=0," in the config...
what should i do?

like this?

square.set_stroke(WHITE, 10)
square.set_background_stroke_width = 0 ...?

or

label1=TexMobject("a")
label1.set_stroke_width=0

....i try all of these orders ... but it seems that it doesn't work...

**Comment by Elteoremadebeethoven** [comment]
Please use the markdown format to make it easier to read the code. Here I show you a [quick](https://guides.github.com/features/mastering-markdown/) tutorial.

This is because you only have the `RemoveBackgroundStrokeWidth` scene, but you also need to have `ChangeBackgroundColor`. `RemoveBackgroundStrokeWidth` is a subclass of `ChangeBackgroundColor`, so you must import it in some way, in the video it is explained that you must use the COMPLETE code, [this](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/extra/faqs/faqs.py) one here. I named it `faqs.py`, so you download and render it normally:

```
python3 -m manim faqs.py RemoveBackgroundStrokeWidth -pl
```

**Comment by barakasamsara** [comment]
> Please use the markdown format to make it easier to read the code. Here I show you a [quick](https://guides.github.com/features/mastering-markdown/) tutorial.
> 
> This is because you only have the `RemoveBackgroundStrokeWidth` scene, but you also need to have `ChangeBackgroundColor`. `RemoveBackgroundStrokeWidth` is a subclass of `ChangeBackgroundColor`, so you must import it in some way, in the video it is explained that you must use the COMPLETE code, [this](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/extra/faqs/faqs.py) one here. I named it `faqs.py`, so you download and render it normally:
> 
> ```
> python3 -m manim faqs.py RemoveBackgroundStrokeWidth -pl
> ```

thanks a lot, i'll try to make it

**Comment by barakasamsara** [comment]
> Please use the markdown format to make it easier to read the code. Here I show you a [quick](https://guides.github.com/features/mastering-markdown/) tutorial.
> 
> This is because you only have the `RemoveBackgroundStrokeWidth` scene, but you also need to have `ChangeBackgroundColor`. `RemoveBackgroundStrokeWidth` is a subclass of `ChangeBackgroundColor`, so you must import it in some way, in the video it is explained that you must use the COMPLETE code, [this](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/extra/faqs/faqs.py) one here. I named it `faqs.py`, so you download and render it normally:
> 
> ```
> python3 -m manim faqs.py RemoveBackgroundStrokeWidth -pl
> ```

![image](https://user-images.githubusercontent.com/36161299/63344097-2f67b000-c382-11e9-957a-bd3b0c2c4b07.png)

I copied the file "faqs.py" and replaced the name to Luciantest20190820faqs
I really don't know what happens... it didn't work...


python3 -m manim Luciantest20190820faqs.py RemoveBackgroundStrokeWidth -pl

**Comment by Elteoremadebeethoven** [comment]
Please read what the terminal is telling you, it is not so difficult.
You are using the most recent version, change the first line: `from big_ol_pile_of_manim_imports import *` with `from manimlib.imports import *`.

**Comment by barakasamsara** [comment]
> Please read what the terminal is telling you, it is not so difficult.
> You are using the most recent version, change the first line: `from big_ol_pile_of_manim_imports import *` with `from manimlib.imports import *`.

I'm so sorry to trouble you again ...with stupid question....
![image](https://user-images.githubusercontent.com/36161299/63515692-ff551400-c51d-11e9-8f24-a77dbfcde98e.png)


![image](https://user-images.githubusercontent.com/36161299/63516133-fb75c180-c51e-11e9-8ba9-a6dc16a63b0d.png)

**Comment by Elteoremadebeethoven** [comment]
That is because you do not have the necessary packages installed on XeLaTeX, you must install them. The packages you need to install are in `manimlib/tex_template.tex`

**Comment by barakasamsara** [comment]
![image](https://user-images.githubusercontent.com/36161299/63537114-9387a100-c547-11e9-9f97-d41fc1fd4dd2.png)
![image](https://user-images.githubusercontent.com/36161299/63537191-c92c8a00-c547-11e9-8b87-eeccd4294e75.png)


i have changed the list before, it means now i need to install all the packages listed on the two documents, right?

and how to install packages listed here?

for example, if i want to install the package "\usepackage[english]{babel}"
can i use the order:

brew install [english]{babel}
......

**Comment by Elteoremadebeethoven** [comment]
No, this is not the way, you have to investigate **how to install LaTeX packages on Mac**, there are many forums where that is explained. BTW, you are using XeLaTeX, so, your tex file is `manimlib/ctex_template.tex` not `manimlib/tex_template.tex`, I forgot tell you that.

**Comment by barakasamsara** [comment]
thanks , i'll try

**Comment by Elteoremadebeethoven** [comment]
Or you can install full MacTeX, see [this](https://www.youtube.com/watch?v=uZj_GQc6pN4).

**Comment by barakasamsara** [comment]
thanks a lot! but i think maybe i have installed full mactex?
it was the same as you said in your video...
i don't what has happened...

![image](https://user-images.githubusercontent.com/36161299/63591615-dac27000-c5e1-11e9-856a-e47d8aaaed10.png)
![image](https://user-images.githubusercontent.com/36161299/63591641-f0d03080-c5e1-11e9-9937-9da8b56d4fa9.png)

**Comment by barakasamsara** [comment]
![image](https://user-images.githubusercontent.com/36161299/63591783-5c1a0280-c5e2-11e9-9077-84f74d421c62.png)
this is the version i installed last time...

**Comment by barakasamsara** [comment]
this is the source code of manim:
![image](https://user-images.githubusercontent.com/36161299/63654604-2a09cb80-c7af-11e9-8dff-5412668b12bc.png)
this is the video
![image](https://user-images.githubusercontent.com/36161299/63654621-5a516a00-c7af-11e9-857e-ff5af9b0ff96.png)

but when i  programmed the same code using python:

![image](https://user-images.githubusercontent.com/36161299/63654636-8f5dbc80-c7af-11e9-9723-0fabb2698d0c.png)


and i'm a little confused about the x_labeled_nums....because the paradox of it...

**Comment by Elteoremadebeethoven** [comment]
You are correct, manim is not configured to use decimals on labels, in video 6 I explain how to add decimals.

**Comment by barakasamsara** [comment]
Thanks a lot...and what's about the packages of latex........

**Comment by Elteoremadebeethoven** [comment]
Do you want to use LaTeX or XeLaTeX? Because in your image here:

https://github.com/Elteoremadebeethoven/AnimationsWithManim/issues/10#issuecomment-523892121

You can clearly read that you are using XeLaTeX, if you do not have it installed that is why it does not work. So better configure in **manimlib/constants.py** `TEX_USE_CTEX = False` instead `True`.

**Comment by Elteoremadebeethoven** [comment]
If that doesn't work, install **TexMaker** (it's free software) open the file tex_template.tex in *manimlib/* and compile it. After that (with TEX_USE_CTEX = False in constants.py) run the scene again.

**Comment by barakasamsara** [comment]
thank a lot ...i have changed False to True before i asked the question to you... so i just now i downloaded the **Texmaker** ,but i don't know what's the meaning of compile...

**Comment by Elteoremadebeethoven** [comment]
See a video tutorial about how to compile in TexMaker.

**Comment by barakasamsara** [comment]
Thanks a lot

**Comment by barakasamsara** [comment]
![image](https://user-images.githubusercontent.com/36161299/63912593-f43f3e00-ca5f-11e9-8822-62cf19ea2cc9.png)
too much awkward...
I'm so sorry to bother you again about this question,,,
I really don't know what the meaning of "compile" here... and i search it in youtube...but it seems that..
