### ISSUE TITLE
Manim is working in terminal but not in python shell

### ISSUE THREAD

**Issue by Iamformanim** [Elteoremadebeethoven/AnimationsWithManim#11]
I have succesfully installed everything as you instructed in your manim tutorial. Code is perfectly working in terminal but the same in code is not working in python shell. I am sharing the code and the error.

> from big_ol_pile_of_manim_imports import *
> 
> class WriteStuff(Scene):
>     def construct(self):
>         example_text = TextMobject(
>             "This is a some text",
>             tex_to_color_map={"text": YELLOW}
>         )
>         example_tex = TexMobject(
>             "\\sum_{k=1}^\\infty {1 \\over k^2} = {\\pi^2 \\over 6}",
>         )
>         group = VGroup(example_text, example_tex)
>         group.arrange_submobjects(DOWN)
>         group.set_width(FRAME_WIDTH - 2 * LARGE_BUFF)
> 
>         self.play(Write(example_text))
>         self.play(Write(example_tex))
>         self.wait()

Error is 

> Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
> [Clang 6.0 (clang-600.0.57)] on darwin
> Type "help", "copyright", "credits" or "license()" for more information.
> >>> 
>  RESTART: /Users/richie/Desktop/Work/maniminstall/manim-master/manim_practice.py 
> 
> Warning (from warnings module):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydub/utils.py", line 165
>     warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
> RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
> >>>

**Comment by Elteoremadebeethoven** [comment]
Manim was not designed to be used in the python shell, if you want to use a development environment you can use PyCharm, [here](https://superuser.com/questions/1470624/how-i-could-execute-this-code-in-pycharm-python-code-with-parameters) how configure it.
