### ISSUE TITLE
How to realize this animation?

### ISSUE THREAD

**Issue by barakasamsara** [Elteoremadebeethoven/AnimationsWithManim#12]
![image](https://user-images.githubusercontent.com/36161299/64478651-cdaaa100-d1dd-11e9-886c-deb18c5920f7.png)

I had try these three orders:
1.dot_2.rotate(110*DEGREES,about_point=dot_1,)
2.dot_2.rotate(110*DEGREES,about_point=np.array([0,1,0]))
3.self.play(ApplyMethod(dot_2.rotate(110*DEGREES,about_point=(0,1,0))))

but all these didn't work...

**Comment by Elteoremadebeethoven** [comment]
[Here](https://github.com/Elteoremadebeethoven/Manim-TB/blob/old_master_1/proy_term/tutorial_manim/positions.py#L423) is the code, replace `Escribe` with `Write`

**Comment by barakasamsara** [comment]
Thanks a lot!
