### ISSUE TITLE
Manim tutorial | 3 - Arrays - CheckFormulaByTXT - what should i do about this...

### ISSUE THREAD

**Issue by barakasamsara** [Elteoremadebeethoven/AnimationsWithManim#13]
this is the code:
![image](https://user-images.githubusercontent.com/36161299/64602052-a37cfd00-d3f0-11e9-998a-f3f60d7a9eb1.png)

and the Traceback:
![image](https://user-images.githubusercontent.com/36161299/64602113-be4f7180-d3f0-11e9-81bd-a317c98f8d72.png)

and I checked the file...
![image](https://user-images.githubusercontent.com/36161299/64602276-138b8300-d3f1-11e9-8192-38dcf8ac9eaa.png)
it means the problem is still in the XeLaTax?...

**Comment by Elteoremadebeethoven** [comment]
This only works in the 3/feb version

**Comment by barakasamsara** [comment]
> This only works in the 3/feb version

thanks...
