### ISSUE TITLE
Problems with "Cairo"

### ISSUE THREAD

**Issue by bq9958** [Elteoremadebeethoven/AnimationsWithManim#19]
Hi, I could run Manim on python 3.7.4. But after installing python3.7.5, Manim just doesn't work. When I tried to run it, it says' ModuleNotFoundError: No module named 'cairo'
And when I changed"import Cairo"into"import cairocffi as cairo". Another problem came up:"ValueError: Got a 480 bytes buffer, needs at least 1639680."
Could you tell me how to solve this?

**Comment by Elteoremadebeethoven** [comment]
You may have to install Pycairo, I don't know what operating system you use (it would be good if you indicated it), but otherwise, I have no idea how to fix it.

**Comment by bq9958** [comment]
The OS I use is the latest Mac OS

**Comment by Carolmyr** [comment]
I have the same issue. And I try to install pycairo. And nothing change.

**Comment by Elteoremadebeethoven** [comment]
Try install manim in Linux using virtualbox, I sugest Ubuntu, Manjaro or ArcoLinux

**Comment by Carolmyr** [comment]
Sorry, I am a complete rookie in programming. Can you specify it? Thank you very much.

**Comment by Elteoremadebeethoven** [comment]
See [this](https://github.com/3b1b/manim/issues/661) or...
Install virtualbox in your Mac (see youtube tutorials), then Install a Linux distro, you can se in youtube "How to install Ubuntu with virtualbox", then you can install manim in that virtual machine using "Install manim in GNU/Linux" video on my yt channel.

**Comment by Carolmyr** [comment]
YiRuis-MacBook-Pro:manim-master carolmyr$ python3 -m manim example_scenes.py WriteStuff -pl
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/carolmyr/Manim/manim-master/manim.py", line 2, in <module>
    import manimlib
  File "/Users/carolmyr/Manim/manim-master/manimlib/__init__.py", line 4, in <module>
    import manimlib.extract_scene
  File "/Users/carolmyr/Manim/manim-master/manimlib/extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "/Users/carolmyr/Manim/manim-master/manimlib/scene/scene.py", line 12, in <module>
    from manimlib.camera.camera import Camera
  File "/Users/carolmyr/Manim/manim-master/manimlib/camera/camera.py", line 9, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'


This the error I get, if it could help by the way.

**Comment by Elteoremadebeethoven** [comment]
https://github.com/3b1b/manim/issues/661

**Comment by Carolmyr** [comment]
yes, I read the link, and try the same thing as he did, but it still not work. (while I am using the terminal on mac.

**Comment by Elteoremadebeethoven** [comment]
In that case then there are only three possibilities, that you are doing it wrong, (that you have installed something wrong) or that it really is a problem, maybe because you use the most recent version of Mac, the modules probably have not yet been updated , or you installed version 3.8, in which case it does not work, you must use version 3.7.
Whatever the option, I can no longer do for you.

**Comment by Elteoremadebeethoven** [comment]
What you have left to do is install Manim in a virtual machine using VirtualBox as I told you in previous comments.

**Comment by Carolmyr** [comment]
I think maybe it is because I am using the mac Catalina. I install python 3.7. Thank you very much. I will go try installing it in virtualbox.

**Comment by Carolmyr** [comment]
I find out that it is important to set up a virtual environment. Here is the link helpful for this problem http://bhowell4.com/manic-install-tutorial-for-mac/.
Thank you very much again.
