### ISSUE TITLE
tengo el siguiente error ""See log output above or the log file: %s" % log_file) Exception: Latex error converting to dvi."

### ISSUE THREAD

**Issue by FlipMordecai** [Elteoremadebeethoven/AnimationsWithManim#2]
Después de buscar entre los archivos de donde venía el error encontre que no se esta conviertiendo el archivo .tex  a .dvi con los textos a animar, también no puedo instalar desde el pip pydvi, que parece ser el modulo que convierte los archivos .tex a .dvi, marcando el error siguente:

ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Gilberto\AppData\Local\Temp\pip-install-tga6ff5_\pydvi\setup.py", line 30, in <module>
        execfile('setup_data.py')
    NameError: name 'execfile' is not defined
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\Gilberto\AppData\Local\Temp\pip-install-tga6ff5_\pydvi\

parece haber un error con el instalador especificamente con "execfile"

sin embargo manim funciona mientras  no escriba texto, tambien ya reinstale el miktex para estar seguro que no es latex el que esta fallando

**Comment by Elteoremadebeethoven** [comment]
Eso posiblemente se debe a que tienes varias versiones de Python.
¿Usas `python -m pip install` o `python3 -m pip install`?. Ya que en Windows eso es un problema, yo recomiendo que siempre uses `python -m pip install`. 
Si eso no sirve usa `pip install`.

**Comment by FlipMordecai** [comment]
ya he intentado con `python -m pip install` me marca el mismo error, tengo python version 3.7, tengo dos versiones de python 32bits y 64bits

**Comment by FlipMordecai** [comment]
`A:\Programas\manim> python -m pip install pydvi
Collecting pydvi
  Using cached https://files.pythonhosted.org/packages/97/8c/501abbb16c50bf5420a166b8c64fbe5f75bca2726d1bbe5dd48e971cc38a/PyDvi-0.1.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Gilberto\AppData\Local\Temp\pip-install-_xi5fu5c\pydvi\setup.py", line 30, in <module>
        execfile('setup_data.py')
    NameError: name 'execfile' is not defined
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\Gilberto\AppData\Local\Temp\pip-install-_xi5fu5c\pydvi\`

este es el error en concreto

**Comment by FlipMordecai** [comment]
```
`A:\Programas\manim> python -m manim example_scenes.py WriteStuff -pl



Traceback (most recent call last):
  File "A:\Programas\manim\manimlib\extract_scene.py", line 153, in main
    scene = SceneClass(**scene_kwargs)
  File "A:\Programas\manim\manimlib\scene\scene.py", line 54, in __init__
    self.construct()
  File "example_scenes.py", line 100, in construct
    tex_to_color_map={"text": YELLOW}
  File "A:\Programas\manim\manimlib\mobject\svg\tex_mobject.py", line 144, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "A:\Programas\manim\manimlib\mobject\svg\tex_mobject.py", line 45, in __init__
    self.template_tex_file_body
  File "A:\Programas\manim\manimlib\utils\tex_file_writing.py", line 21, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "A:\Programas\manim\manimlib\utils\tex_file_writing.py", line 69, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: A:\Programas\manim\manimlib\files\Tex\180ac34c70629cf1.log`
```


todo esto es el error de cuando trato de compilar la clase` WriteStuff`, si cambio el archivo de `WriteStuff` por `OpeningManimExample` marca casi el mismo error cambiando en la última linea `\manim\manimlib\files\Tex\180ac34c70629cf1.log` por `\manim\manimlib\files\Tex\6220a5dfffe0395c.log`

**Comment by Elteoremadebeethoven** [comment]
Intenta compilar el archivo tex_template.tex que está en manimlib/, usando

```
latex tex_template.tex
```

Eso te debe de generar un archivo .dvi que dige "YourTextHere" y otros archivos. Si no lo puedes compilar es porque MikTeX no se agregó a la variable PATH, entonces tienes que ir a las variables del sistema a comprobar que MikTeX esté agregado, generalmente es

`C:\Program files\MikTeX2.9\miktex\bin\x64`

En caso de que no esté, agrégalo buscando la ubicación del binario de MikTeX en tu PC.

**Comment by Elteoremadebeethoven** [comment]
Si no tienes visor de archivos .dvi entonces compílalo usando pdflatex en lugar de latex para que te genere un archivo .pdf

**Comment by FlipMordecai** [comment]
buen día, he intentado compilar `latex tex_template.tex` a lo que marco lo siguiente, mostrando este error en latex, ¿tiene idea de como repararlo?:

`A:\Programas\manim\manimlib>latex tex_template.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7050 64-bit)
entering extended mode
(tex_template.tex
LaTeX2e <2018-12-01>
(A:\Programas\latex\tex/latex/standalone\standalone.cls
Document Class: standalone 2018/03/26 v1.3a Class to compile TeX sub-files stan
dalone
(A:\Programas\latex\tex/latex/tools\shellesc.sty)
(A:\Programas\latex\tex/generic/oberdiek\ifluatex.sty)
(A:\Programas\latex\tex/generic/oberdiek\ifpdf.sty)
(A:\Programas\latex\tex/generic/ifxetex\ifxetex.sty)
(A:\Programas\latex\tex/latex/xkeyval\xkeyval.sty
(A:\Programas\latex\tex/generic/xkeyval\xkeyval.tex
(A:\Programas\latex\tex/generic/xkeyval\xkvutils.tex
(A:\Programas\latex\tex/generic/xkeyval\keyval.tex))))
(A:\Programas\latex\tex/latex/standalone\standalone.cfg)
(A:\Programas\latex\tex/latex/base\article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(A:\Programas\latex\tex/latex/base\size10.clo))
(A:\Programas\latex\tex/latex/preview\preview.sty
(A:\Programas\latex\tex/generic/luatex85\luatex85.sty)
(A:\Programas\latex\tex/latex/preview\prtightpage.def)))
(A:\Programas\latex\tex/latex/base\inputenc.sty)

**! LaTeX Error: File `T1.sty' not found.**

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:`

**Comment by Elteoremadebeethoven** [comment]
Eso quiere decir que no instalaste todas las paqueterías de MikTeX, seguramente sólo instalaste la versión básica. Tienes dos opciones, descargar la versión completa como se ve en mi tutorial en YouTube, o descargar un entorno de desarrollo, como TexMaker, lo instalas (es sofware libre), abres tex_template.tex com TexMaker y compilas el código. El propio TexMaker te pedirá descargar las paqueterías faltantes. Las instalas y en teoría, cuando te genere el .pdf ya podrás renderizar los videos. En caso de que no sea así, tendrás que reinstalar MikTeX, pero la versión FULL, que pesa como 4GB.

**Comment by FlipMordecai** [comment]
ya instale la versión completa de miktex y aún me marca que no encuentra el paquete **T1.sty**:

File `T1.sty' not found.

 de igual forma instale el TexMaker, me marca el mismo error de que falta `T1.sty`, no sé como instalar las librerias faltantes desde texmaker, ya cheque y esta agregado al path miktex, podría ayudarme con la instalación,

 Ahora tengo una solución parcial, lo que he hecho es modificar el archivo,` tex_template.tex` en la parte donde se declaran los paquetes he comentado la linea siguiente:


`%\usepackage{T1}{fontenc}
`

finalmente lo remplace con: `\usepackage[utf8]{inputenc}
`

De esta forma ya compilan los videos sin marcar error, mi duda es si a futuro ocuparé ese paquete de latex `T1.sty`, porque al agregar` \usepackage{latin1}{inputenc}` marca el mismo error que con `T1.sty`, no sé como instalar estos paquetes de latex, espero pueda ayudarme.

**Comment by Elteoremadebeethoven** [comment]
Ya vi tu error, no es
```
\usepackage{T1}{fontenc}
```
Es
```
\usepackage[T1]{fontenc}
```
Con corchetes.
Puedo ver que esto te ocurrió debido a que así se mostró en el video, ya fijé un comentario para que esto no vuelva a suceder. Gracias.

**Comment by FlipMordecai** [comment]
Muchas gracias, de verdad espero que prosperé su canal

**Comment by Elteoremadebeethoven** [comment]
Gracias!

**Comment by gargVader** [comment]
@Elteoremadebeethoven I have the same problem. Please post the same solution in english in #623
