### ISSUE TITLE
type object 'Animation' has no attribute 'mobject'

### ISSUE THREAD

**Issue by asustnt3** [Elteoremadebeethoven/AnimationsWithManim#20]
windows 10 64bit  python3.7.2  manimlib-0.1.10

when I tpye the code in update_successions/update_successions.py
class SuccessionExample1(Scene):
there is an error when run this class in Succession(Animation, Mobject(), {"run_time": 2.1},
AttributeError: type object 'Animation' has no attribute 'mobject'
I dont know why

class SuccessionExample1Fail(Scene):
...
self.play(
            ShowCreationThenDestruction(dashed_line, submobject_mode="lagged_start", run_time=5),
            Succession(Animation, Mobject(), {"run_time": 2.1},
            Write, text)
        )

thank you for your time

**Comment by Elteoremadebeethoven** [comment]
You are using the most recent version, so, you have to use [this](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/update_successions/successions_in_recent_versions.py).
