### ISSUE TITLE
Error when trying to use text like arrays

### ISSUE THREAD

**Issue by KienPS** [Elteoremadebeethoven/AnimationsWithManim#21]
I write this in my code, and it works fine:
`title = TexMobject("\\frac{tanx - \\sqrt{3}}{2cosx + 1} = 0")`
But when I write like this:
`title = TexMobject("\\frac{","tanx","-\\sqrt{3}}{","2cosx","+1} = 0")`
I got `Xelatex error converting to dvi`
What's the problem here?

**Comment by Elteoremadebeethoven** [comment]
Like I said in my [video](https://www.youtube.com/watch?v=DGSj7weT-y8&t=8m37s) don't use `\frac` to fragment formulas, use `\over`.
