### ISSUE TITLE
Necesito ayuda para poder instalar manim. Mi problema básicamente es con la instalación de Pycairo. De igual forma instalé ffmpeg de una diferente, pero si se instaló, solo que no me instala el pycairo.

### ISSUE THREAD

**Issue by ismALbert** [Elteoremadebeethoven/AnimationsWithManim#22]
# __**WARNING**__
**Before writing an issue, please check the following links if someone has already resolved your question. If you are asking things that have already been resolved I will have no choice but to close your issue.**

* [Manim issues](https://github.com/3b1b/manim/issues?q=is%3Aissue+is%3Aclosed)
* [Stackoverflow](https://stackoverflow.com/questions/tagged/manim)
* [Reddit](https://www.reddit.com/r/manim/)
* [Official documentation](https://www.eulertour.com/learn/manim/)
* [My documentation](https://elteoremadebeethoven.github.io/manim_3feb_docs.github.io/html/index.html)
* [Todd tutorial](https://talkingphysics.wordpress.com/2019/01/08/getting-started-animating-with-manim-and-python-3-7/)
* [Malhora tutorial](https://github.com/malhotra5/Manim-Tutorial)
* [My tutorials](https://www.youtube.com/watch?v=ENMyFGmq5OA&list=PL2B6OzTsMUrwo4hA3BBfS7ZR34K361Z8F)

**You can joined to the Discord community [here](https://discordapp.com/invite/mMRrZQW)**

# Points to consider before writing your issue

* This repository works with the Manim version of February 3, unless otherwise indicated. If your code does not work, check that you are using the correct version.
* At the moment Manim works with Python 3.7, not with 3.8. This is because several of the dependencies have not yet been updated.
* If the terminal throws an error, please write it completely with the markdown format.
* Be clear and specific with your problem, share the code (and files, if applicable) and the command you use when rendering the video.

# Fast markdown tutorial.
## Inline code:

**INPUT**

The code is \`TexMobject\` write \`TeX\`.

**OUTPUT**

The code is `TexMobject` write `TeX`.

## Multiline code

**INPUT**

My code is:

\`\`\`python

Here is

a multiline

code

\`\`\`

**OUTPUT**

My code is:

```python
Here is

a multiline

code
```

**[LEARN MORE HERE](https://guides.github.com/features/mastering-markdown/#what)**

**Comment by Elteoremadebeethoven** [comment]
Escribe tu problema, no me estás diciendo nada, tienes que escribir todos tus logs (lo que te dice la terminal) y lo que sea necesario para ayudarte, cerraré este issue pero escribe otro con el formato de Markdown.
