### ISSUE TITLE
Hola! Tengo una duda respecto a los gráficos en manim

### ISSUE THREAD

**Issue by ErnTreumun** [Elteoremadebeethoven/AnimationsWithManim#24]
Hola! sin antes disculparme con esta básica pregunta, quería plantearte una duda que me surgió al realizar gráficos de funciones, pues no encontré información en internet respecto esta.

Bien, mi duda es que, ¿Cómo hago para disminuir el tamaño de los ejes y de la función ?, pues si escalo la variable "graph" sólo se escala el gráfico de mi función, mas no los ejes "x" e "y". Además, ¿Cómo hago para animar un movimiento de esta? Había pensado en definir un mismo gráfico dos veces, con distintas posiciones, pero esto resulta imposible pues los "ejes" se definen una sóla vez

Espero se entiendan mis preguntas
Saludos y de ante mano muchas gracias !

**Comment by Elteoremadebeethoven** [comment]
Puedes crear los ejes que quieras usando `Axes`, ver [aquí](https://github.com/3b1b/manim/blob/48f2a1ec3c86f3ad26b6b1292b6917149005cbab/manimlib/mobject/coordinate_systems.py#L129), ya que este objeto tiene el método [`get_graph()`](https://github.com/3b1b/manim/blob/48f2a1ec3c86f3ad26b6b1292b6917149005cbab/manimlib/mobject/coordinate_systems.py#L88), y puedes modificar los parámetros de CONFIG (ve mi video de Preguntas frecuentes)
