### ISSUE TITLE
MoveAlongPathWithAngle

### ISSUE THREAD

**Issue by emailtowa** [Elteoremadebeethoven/AnimationsWithManim#26]
Hi there :-)

I was looking for the code which produces the "arrow" to follow the curve.
Thank you for providing this useful part of the code.

Best and sincerely greetings,
Thomas

![MAPWA](https://user-images.githubusercontent.com/39776780/78771536-99c07580-7990-11ea-87c0-b1e6877c91d8.PNG)

**Comment by Elteoremadebeethoven** [comment]
The code is shown in the video (see the description of the video), find it yourself.
