### ISSUE TITLE
11:25 Installing manim for windows video. Error

### ISSUE THREAD

**Issue by gargVader** [Elteoremadebeethoven/AnimationsWithManim#3]
I am stuck 11:25 
When I enter the command shown in your video it shows the following output. Confused.

![Screenshot (14)](https://user-images.githubusercontent.com/52619530/60765823-fe773880-a0bd-11e9-9fea-fdf0877cf2fa.png)

**Comment by Elteoremadebeethoven** [comment]
It is `SquareToCircle`, you wrote `SquareTocircle`, please be more careful, This way we avoid unnecessary problems.
