### ISSUE TITLE
Please help with that parametric surface

### ISSUE THREAD

**Issue by BETAPANDERETA** [Elteoremadebeethoven/AnimationsWithManim#37]
### Please, I want to know or some guide to plot that parametric surface 
First one I want to thank you for this content, it's amazing.
Returning with my problem I mean something like this: 
![cassini4b](https://user-images.githubusercontent.com/49081413/82741907-116a1a00-9d1d-11ea-9015-378768bd75cd.gif)
I saw that post [http://lemur.cmp.uea.ac.uk/Research/ivis/backup/PhD/Latest/Paul%20Bourke%20Screenshots/Eggs,%20melons,%20and%20peanuts%20-%20Cassini%20Oval.htm](url) to guide me, but I can´t understand how can I use that info. to create the parametric surface using `ParametricSurface(lambda u, v: np.array([ # The parameters of that surface]))` 

I'll be very greatful if you can help me.
I'm trying with this 
```python
lemnisBer = ParametricSurface(
                lambda u, v: np.array([
                   np.cos(u) / (np.sin(u)**2 + 1),
                   0
                   np.cos(u) * np.sin(u) / (np.sin(u)**2 + 1),
                ]), u_min=TAU, u_max=TAU, checkerboard_colors=[YELLOW_E,YELLOW_E],
                resolution=(15, 32)).scale(1.5)
```
But that don't graph a peanut or something similar.
Best and sincerely greetings,

**Comment by Elteoremadebeethoven** [comment]
Since this is not a question about installation or my tutorials, I recommend that you watch my **How to ask your questions about manim** video. If you are still interested in me personally solving your question, I would charge you 15 USD via PayPal.

**Comment by BETAPANDERETA** [comment]
Oh thanks you, I solved that , I did the graph that I want, but I´m very grateful with your tutorial and start guides.
