### ISSUE TITLE
Hoping for a reply

### ISSUE THREAD

**Issue by sraut92** [Elteoremadebeethoven/AnimationsWithManim#38]
I had a problem rendering the WriteStuff command as i got an error of latex not recognized as a batch file. But then after going through your thread on the issue i reinstalled latex and i was able to play the command.

    However now when i am trying to run render the WhatIsCONFIG command i get the same error of latex not recognized as a batch file. I tried running the WriteStuff command and it works just fine. But the Whatisconfig gives the error. 

I think the problem is with the .py files and the code regarding dvi. however as i am not from the background of computer science i do not know how to proceed

**Comment by Elteoremadebeethoven** [comment]
You have to use the 3/feb release, that code does't work with the most recent

**Comment by sraut92** [comment]
Does that mean I will have to use packages in the requirement text only?
Also I find it weird that latex is not recognised as a batch file yet the
Writestuff file plays efficiently.  Is there are page where I can know how
to use new version of manim? Thank you in advance.
