### ISSUE TITLE
RateFunctions in rate_functions_scenes.py:123 doesn't compile the names of rate functions that have underscoores

### ISSUE THREAD

**Issue by csrabak** [Elteoremadebeethoven/AnimationsWithManim#40]
Whereas we can see the video of the example running, attempting to compile and generate de scene RateFunctions using the Manin-TB clone (Feb/2019) chokes the LaTeX generation.

If the names of the rate functions that have an undescore are commented out, the scene is generated, albeit with less examples...

**Comment by Elteoremadebeethoven** [comment]
My Manim-TB repo is pretty sloppy, it's normal, use another version instead.
