### ISSUE TITLE
Creature Malformation

### ISSUE THREAD

**Issue by phi19** [Elteoremadebeethoven/AnimationsWithManim#50]
So, I am with manim version 3 feb 2019
I followed this tutorial: https://youtu.be/KGdA8IB6JL0
I changed ALL the "NumberCreature" with "criatura_phi"
I have this code:

class phiCena(Scene):
def construct(self):
Ale=Alex().to_edge(DOWN)
palabras_ale = TextMobject("Learn to do \\animations with me!!")
self.add(Ale)
###
self.play(criatura_phiSays(
Ale, palabras_ale,
bubble_kwargs = {"height" : 4, "width" : 6},
target_mode="speaking"
))
###
for k in range(0, 4):
self.wait()
self.play(Blink(Ale))

When I render WITHOUT the middle-part (the part surrounded by the ###), it all goes right (the phi_Cena_ok gif).
![phiCena_ok](https://user-images.githubusercontent.com/70387940/97888507-1d71f300-1d23-11eb-9f0c-e59700de34bf.gif)
But when I try to render WITH the middle-part, something weird happens (the phi_Cena_not_ok gif).
![phiCena_not_ok](https://user-images.githubusercontent.com/70387940/97888558-295db500-1d23-11eb-8de1-8f0e8f8a5a64.gif)
(I render it like mp4 video, but I had to convert them to gifs to pu them here :P)

**Comment by Elteoremadebeethoven** [comment]
That is because you don't have `number_creature_speaking.svg` file in your svg folder, you have to create one, all `target_mode=""som` have to add a new svg file named as `number_creature_some.svg`.

**Comment by phi19** [comment]
Wait, what? Sorry, did not understand anything.
Do I have to create a `number_creature_speaking.svg` on the svg folder? Still doesn't work
Also, what do you mean with " all `target_mode=""som` " ??
And what I have to do about the thing "have to add a new svg file named as `number_creature_some.svg`"?
Do I have to make any change in the code?
