### ISSUE TITLE
Manim Installation Unsuccesfull "IndexError: list index out of range"

### ISSUE THREAD

**Issue by mike090y9** [Elteoremadebeethoven/AnimationsWithManim#52]
after the installation of manim I tried to use the command line in the command promt

python -m manim example_scenes.py SquareToCircle -pl

this works just fine, the problem araise when i try to use the command

python -m manim example_scenes.py WriteStuff -pl

![manim-idex-error](https://user-images.githubusercontent.com/20775038/104865767-7d2f7180-5902-11eb-8a17-722889a42686.PNG)

and then I got that, looking through different forums I found this

![manim-idex-error2](https://user-images.githubusercontent.com/20775038/104866072-47d75380-5903-11eb-9c3f-444a7101e814.PNG)

I can tell that if I do as it is said it works for the WriteStuff, but then after even the most basic exercise related to text generation fails which remaind me of this

![manim-idex-error3](https://user-images.githubusercontent.com/20775038/104866200-9553c080-5903-11eb-8ddc-70acd23279e3.PNG)

**Comment by P0intMaN** [comment]
Hey Mike, I also faced this problem when i was starting off with manim. The only way to solve this problem is to download and install all the tex packages form MikTex. It will definitely work after this step.

**Comment by P0intMaN** [comment]
If you have any doubt, don't hesitate to share.. Would love to help
