### ISSUE TITLE
Install requirements for Cairo / Ubuntu 18.04

### ISSUE THREAD

**Issue by francofusco** [Elteoremadebeethoven/AnimationsWithManim#8]
Hello! I just wanted to report a minor issue that I encountered, to help people in the future. I am running on Ubuntu 18.04, and had both python 3.6 and python 3.7 already installed. When installing the dependencies for Cairo, I encountered no problem. However, when installing Cairo itself, I get an error about a missing header "Python.h". The reason is simply that when executing
```bash
sudo apt install python3-dev
```
the package manager installed the headers for python 3.6. Installing explicitly the correct version, *i.e.*, `python3.7-dev`, solved the issue.

Hope it helps! :)

**Comment by Elteoremadebeethoven** [comment]
Thank you very much for this, but I think it would be better if you sent a pull request to the [official documentation](https://github.com/3b1b/manim/blob/master/docs/source/installation/linux.rst), in this way the developers can add it to the repository.

**Comment by francofusco** [comment]
Hi, I considered doing what you suggested and forked manim on my pc. However, looking into its documentation, python 3.7 does not seem to be a "strict" requirement. Indeed, I just gave it a try and it *seems* to be working also with python 3.6.8. Perhaps I missed some points, so if you know that 3.7 should be used instead I would be more than happy to be aware of future issues I could encounter by using 3.6 instead!

That said, I think the best would be to add a note in this repo to tell that python 3.6 could work as well. I would still mention the `python3-dev` vs. `python3.7-dev` issue, it might be helpful for some people. I can do it and send you a PR, or let me know if you'd like to do it directly. At the same time, I will prepare a PR to the main manim repo to add in the docs what you need to install Cairo - from what I see, it is not mentioned at all. In there, I can try to warn about the `python3.x-dev` issue.

Let me know what you think!

**Comment by francofusco** [comment]
> python 3.7 does not seem to be a "strict" requirement

Well, I was of course mistaken. It is written in the beginning of the [README](https://github.com/3b1b/manim/blob/master/README.md) that

> Manim runs on python 3.7

I will contact them to know if python 3.6 is ok as well, and also to propose the mentioned PR. Sorry for bothering :sweat_smile:

**Comment by Elteoremadebeethoven** [comment]
No problem.
